/**
 * 🔹 DIP COMPLIANCE: Dependency Injection Types
 * Central place for all DI container type constants
 */

export const TYPES = {
  // Repository Types
  IUserRepository: Symbol.for("IUserRepository"),
  IUserCrudRepository: Symbol.for("IUserCrudRepository"),
  IMentorQueryRepository: Symbol.for("IMentorQueryRepository"),
  IUserStatusRepository: Symbol.for("IUserStatusRepository"),
  IUserStatsRepository: Symbol.for("IUserStatsRepository"),
  IAdminRepository: Symbol.for("IAdminRepository"),
  IServiceRepository: Symbol.for("IServiceRepository"),
  IMentorRepository: Symbol.for("IMentorRepository"),
  IMenteeRepository: Symbol.for("IMenteeRepository"),
  IBookingRepository: Symbol.for("IBookingRepository"),
  IPaymentRepository: Symbol.for("IPaymentRepository"),
  IMessageRepository: Symbol.for("IMessageRepository"),
  IChatRepository: Symbol.for("IChatRepository"),
  INotificationRepository: Symbol.for("INotificationRepository"),
  IOTPRepository: Symbol.for("IOTPRepository"),
  IScheduleRepository: Symbol.for("IScheduleRepository"),
  ISlotRepository: Symbol.for("ISlotRepository"),
  IVideoCallRepository: Symbol.for("IVideoCallRepository"),
  IWalletRepository: Symbol.for("IWalletRepository"),
  ITestimonialRepository: Symbol.for("ITestimonialRepository"),
  IPriorityDmRepository: Symbol.for("IPriorityDmRepository"),
  IContactMessageRepository: Symbol.for("IContactMessageRepository"),
  IAppealRepository: Symbol.for("IAppealRepository"),
  IBlockedRepository: Symbol.for("IBlockedRepository"),
  IBotConversationRepository: Symbol.for("IBotConversationRepository"),
  IBotRateLimitRepository: Symbol.for("IBotRateLimitRepository"),
  IPolicyRepository: Symbol.for("IPolicyRepository"),
  IFAQRepository: Symbol.for("IFAQRepository"),
  ICareerProfessional: Symbol.for("ICareerProfessional"),
  ICareerCollege: Symbol.for("ICareerCollege"),
  ICareerSchool: Symbol.for("ICareerSchool"),

  // Service Types
  IUserAuthService: Symbol.for("IUserAuthService"),
  IUserService: Symbol.for("IUserService"),
  IMentorService: Symbol.for("IMentorService"),
  IMenteeService: Symbol.for("IMenteeService"),
  IAdminService: Symbol.for("IAdminService"),
  IAdminAuthService: Symbol.for("IAdminAuthService"),
  IServiceServices: Symbol.for("IServiceServices"),
  IBookingService: Symbol.for("IBookingService"),
  IPaymentService: Symbol.for("IPaymentService"),
  IMessageService: Symbol.for("IMessageService"),
  IChatService: Symbol.for("IChatService"),
  INotificationService: Symbol.for("INotificationService"),
  IOTPService: Symbol.for("IOTPService"),
  ICalenderService: Symbol.for("ICalenderService"),
  IVideoCallService: Symbol.for("IVideoCallService"),
  ITestimonialService: Symbol.for("ITestimonialService"),
  IContactMessageService: Symbol.for("IContactMessageService"),
  IAppealService: Symbol.for("IAppealService"),
  IChatbotService: Symbol.for("IChatbotService"),
  IAIService: Symbol.for("IAIService"),
  IUploadService: Symbol.for("IUploadService"),

  // Controller Types
  IUserAuthController: Symbol.for("IUserAuthController"),
  IUserController: Symbol.for("IUserController"),
  IMentorController: Symbol.for("IMentorController"),
  IMenteeController: Symbol.for("IMenteeController"),
  IAdminController: Symbol.for("IAdminController"),
  IAdminAuthController: Symbol.for("IAdminAuthController"),
  IBookingController: Symbol.for("IBookingController"),
  IPaymentController: Symbol.for("IPaymentController"),
  ISocketController: Symbol.for("ISocketController"),
  INotificationController: Symbol.for("INotificationController"),
  IVideoCallController: Symbol.for("IVideoCallController"),
  IContactController: Symbol.for("IContactController"),
  IAppealController: Symbol.for("IAppealController"),
  IChatbotController: Symbol.for("IChatbotController"),
  IUploadController: Symbol.for("IUploadController"),
  IWebHookController: Symbol.for("IWebHookController"),
  ISecureVideoProxyController: Symbol.for("ISecureVideoProxyController"),

  // Utility Types
  RedisTokenService: Symbol.for("RedisTokenService"),
} as const;